apiVersion: v1
kind: Service
metadata:
  name: {{ include "mibserver.fullname" . }}
  labels:
    {{- include "mibserver.labels" . | nindent 4 }}
spec:
  type: {{ (.Values.service).type | default "ClusterIP" }}
  ports:
    - port: {{ (.Values.service).port | default 80 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mibserver.selectorLabels" . | nindent 4 }}
